enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-version = "dev"
arch = "both"
included-patches = "'Hide music video ads' 'Enable exclusive audio playback' 'Navigation bar' 'Hide ''Get Music Premium''' 'Bypass certificate checks' 'Remove background playback restrictions' 'Sanitize sharing links'"
exclusive-patches = true

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-version = "dev"
arch = "both"
included-patches = "'Hide ads' 'Video ads' 'Navigation buttons' 'Hide player flyout menu items' 'Change start page' 'Remove background playback restrictions' 'Bypass URL redirects' 'Sanitize sharing links'"
exclusive-patches = true
